---
# Debian tasks file for ansible-role-duo-unix/

- name: "Install required packages (Debian)"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: "Import Duo Security Repository Key (Debian)"
  ansible.builtin.apt_key:
    file: /tmp/DUO-GPG-PUBLIC-KEY.asc
    state: present

- name: "Create Duo Security Repository (Debian)"
  ansible.builtin.apt_repository:
    repo: "deb https://pkg.duosecurity.com/{{ ansible_distribution }} {{ ansible_distribution_release }} main"
    validate_certs: no
    state: present

- name: "Install duo_unix package (Debian)"
  ansible.builtin.apt:
    name: "duo_unix"
    state: present

- name: "Deploy pam_duo.conf Template (Debian)"
  ansible.builtin.template:
    src: pam_duo.j2
    dest: /etc/duo/pam_duo.conf
    force: yes

- name: "Set auth pam_unix.so to required in common_auth (Debian)"
  community.general.pamd:
    name: common_auth
    type: auth
    control: '[success=1 default=ignore]'
    module_path: pam_unix.so
    new_control: requisite
    backup: true

- name: "Add auth pam_duo.so to common_auth (Debian)"
  community.general.pamd:
    name: common_auth
    type: auth
    control: requisite
    module_path: pam_unix.so
    new_type: auth
    new_control: '[success=1 default=ignore]'
    new_module_path: pam_duo.so
    state: after

- name: "Disable @include common-auth statement in sshd (Debian)"
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sshd
    search_string: "@include common-auth"
    line: "#@include common-auth"
    backup: true

- name: "Insert pam_duo.so statement in sshd (Debian)"
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sshd
    insertafter: "^#@include common-auth"
    line: "auth  [success=1 default=ignore] pam_duo.so"

- name: "Add auth pam_deny.so to ssh (Debian)"
  community.general.pamd:
    name: ssh
    type: auth
    control: '[success=1 default=ignore]'
    module_path: pam_duo.so
    new_type: auth
    new_control: requisite
    new_module_path: pam_deny.so
    state: after

- name: "Add auth pam_permit.so to ssh (Debian)"
  community.general.pamd:
    name: ssh
    type: auth
    control: requisite
    module_path: pam_deny.so
    new_type: auth
    new_control: required
    new_module_path: pam_permit.so
    state: after
