---
# tasks file for ansible-role-duo-unix/

- name: "Include OS-specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yaml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Get OpenSSH installed version"
  ansible.builtin.set_fact:
    openssh_version: "{{ ansible_facts.packages['openssh-server'][0].version }}"

- ansible.builtin.include_tasks: Debian.yaml
  when: ansible_facts['os_family'] == 'Debian'

- ansible.builtin.include_tasks: RedHat.yaml
  when: ansible_facts['os_family'] == 'RedHat'