---
# tasks file for ansible-role-duo-unix/

- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yaml"
        - "{{ ansible_os_family }}.yml"
        - default.yaml
        - default.yml
      paths:
        - "vars"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Install yum-utils package, if not already installed"
  ansible.builtin.package:
    name: "yum-utils"
    state: present
  when:
    - '"yum-utils" not in ansible_facts.packages'
    - ansible_os_family == 'RedHat'

- name: "Import Duo Security Repository Key"
  block:
    - name: "Download latest Duo Security Repository Key"
      ansible.builtin.get_url:
        url: https://duo.com/DUO-GPG-PUBLIC-KEY.asc
        dest: /tmp/
      delegate_to: localhost
    - name: "Transfer Duo Security Repository Key to host"
      ansible.builtin.copy:
        src: /tmp/DUO-GPG-PUBLIC-KEY.asc
        dest: /tmp/
        owner: root
        group: root
        mode: 0644
        remote_src: no
    - name: "Import Duo Security Repository Key (RedHat)"
      rpm_key:
        key: /tmp/DUO-GPG-PUBLIC-KEY.asc
        state: present
      when: ansible_os_family == 'RedHat'
    - name: "Import Duo Security Repository Key (Debian)"
      apt_key:
        url: /tmp/DUO-GPG-PUBLIC-KEY.asc
        state: present
      when: ansible_os_family == 'Debian'

- name: "Add Duo Security Repository"
  block:
    - name: "Check if host is registered to a Spacewalk server"
      ansible.builtin.stat:
        path: /etc/sysconfig/rhn/systemid
      register: systemid
      when:
        - '"rhncfg-client" in ansible_facts.packages'
        - ansible_distribution == 'CentOS'
    - name: "Check if Duo Security Repository is added via Spacewalk"
      shell: rhn-channel --list | grep -i "duo"
      register: repo
      when: systemid.stat.exists
    - name: "Create Duo Security Repository (RedHat)"
      ansible.builtin.yum_repository:
        name: duosecurity
        description: "Duo Security Repository"
        baseurl: "https://pkg.duosecurity.com/{{ ansible_distribution }}/$releasever/$basearch"
        enabled: yes
        gpgcheck: no
        state: present
      when: not systemid.stat.exists or repo.rc != 0
    - name: "Create Duo Security Repository (Debian)"
      ansible.builtin.apt_repository:
        repo: "deb https://pkg.duosecurity.com/{{ ansible_distribution }} {{ ansible_distribution_release }} main"
        validate_certs: no
        state: present
      when: ansible_os_family == 'Debian'

- name: "Install duo_unix package"
  ansible.builtin.package:
    name: "duo_unix"
    state: present

- name: "Deploy pam_duo.conf Template"
  template:
    src: pam_duo.j2
    dest: /etc/duo/pam_duo.conf
    force: yes

- name: "Configure SSH Daemon authentication order in pamd"
  block:
    - name: "Add auth pam_env.so to sshd"
      pamd:
        name: sshd
        type: auth
        control: substack
        module_path: password-auth
        new_type: auth
        new_control: required
        new_module_path: pam_env.so
        state: after
    - name: "Add auth pam_duo.so to sshd"
      pamd:
        name: sshd
        type: auth
        control: required
        module_path: pam_env.so
        new_type: auth
        new_control: sufficient
        new_module_path: pam_duo.so
        state: after
    - name: "Add auth pam_deny.so to sshd"
      pamd:
        name: sshd
        type: auth
        control: sufficient
        module_path: pam_duo.so
        new_type: auth
        new_control: required
        new_module_path: pam_deny.so
        state: after
    - name: "Disable substack password-auth to sshd"
      pamd:
        name: sshd
        type: auth
        control: substack
        module_path: password-auth
        state: absent

- name: "Update SSH configuration"
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication {{ password_authentication }}"
    state: present
    validate: 'sshd -T -f %s'
    mode: 0644
    backup: yes
  notify: "Restart SSH Daemon"