---
# tasks file for ansible-role-duo-unix/

- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yaml"
        - "{{ ansible_os_family }}.yml"
        - default.yaml
        - default.yml
      paths:
        - "vars"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Install yum-utils package, if not already installed"
  ansible.builtin.package:
    name: "yum-utils"
    state: present
  when:
    - '"yum-utils" not in ansible_facts.packages'
    - ansible_os_family == 'RedHat'

- name: "Import Duo Security Repository Key"
  block:
    - name: "Download latest Duo Security Repository Key"
      ansible.builtin.get_url:
        url: https://duo.com/DUO-GPG-PUBLIC-KEY.asc
        dest: /tmp/
      delegate_to: localhost
    - name: "Transfer Duo Security Repository Key to host"
      ansible.builtin.copy:
        src: /tmp/DUO-GPG-PUBLIC-KEY.asc
        dest: /tmp/
        owner: root
        group: root
        mode: 0644
        remote_src: no
    - name: "Import Duo Security Repository Key (RedHat)"
      rpm_key:
        key: https://duo.com/DUO-GPG-PUBLIC-KEY.asc
        state: present
      when: ansible_os_family == 'RedHat'
    - name: "Import Duo Security Repository Key (Debian)"
      apt_key:
        url: https://duo.com/DUO-GPG-PUBLIC-KEY.asc
        state: present
      when: ansible_os_family == 'Debian'

- name: "Add Duo Security Repository"
  block:
    - name: "Check if host is registered to a Spacewalk server"
      command: rhncfg-client get
      register: rhncfg
      failed_when: "'FAILED' in rhncfg.stderr"
      when:
        - '"rhncfg-client" in ansible_facts.packages'
        - ansible_distribution == 'CentOS'
    - name: "Check if Duo Security Repository is added via Spacewalk"
      shell: rhn-channel --list | grep -i "duo"
      register: repository
      #failed_when: "'FAILED' in repository.stderr"
      #ignore_errors: true
      when:
        - rhncfg.rc == 0
    - name: "Create Duo Security Repository"
      ansible.builtin.yum_repository:
        name: duosecurity
        description: "Duo Security Repository"
        baseurl: "https://pkg.duosecurity.com/{{ ansible_distribution }}/$releasever/$basearch"
        enabled: yes
        gpgcheck: no
      when: rhncfg.rc == 1 or repository.rc != 0
