---
# tasks file for ansible-role-duo-unix/

- name: "Include OS-specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yaml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when:
    - ansible_facts.packages is not defined

- name: "Get OpenSSH installed version"
  ansible.builtin.set_fact:
    openssh_version: "{{ ansible_facts.packages['openssh-server'][0].version }}"

- name: "Download latest Duo Security Repository Key"
  ansible.builtin.get_url:
    url: https://duo.com/DUO-GPG-PUBLIC-KEY.asc
    dest: /tmp/
    mode: 0644
  delegate_to: localhost

- name: "Transfer Duo Security Repository Key to host"
  ansible.builtin.copy:
    src: /tmp/DUO-GPG-PUBLIC-KEY.asc
    dest: /tmp/
    owner: root
    group: root
    mode: 0644
    remote_src: no

- name: "Include tasks from Debian playbook"
  ansible.builtin.include_tasks: Debian.yaml
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: "Include tasks from RedHat playbook"
  ansible.builtin.include_tasks: RedHat.yaml
  when:
    - ansible_facts['os_family'] == 'RedHat'

- name: "Include tasks from OpenSSH playbook"
  ansible.builtin.include_tasks: OpenSSH.yaml
